TAG5006.Hex: tigerr.obj tigerb.obj tigerd.obj \
           tigerc.obj tigeri.obj tigerf.obj \
           tigerk.obj tigerm.obj tigerp.obj \
           tigers.obj tigert.obj tigerw.obj \
           tigerx.obj tigerz.obj \
    LIB\tigerl.lib
    echo Linking  ...
    L51 @linkfile >> message
    OH51 TAG5006

TIGERr.OBJ: tigerr.asm
    echo Compiling tigerr.asm (assembler run time directives)
    echo Compiling tigerr.asm >> message
    A51 tigerr.asm $NOPRINT $OBJECT(TIGERr.OBJ) >> message

TIGERb.OBJ: tigerb.c tiger.h
    echo Compiling tigerb.c (battery protected variables)
    echo Compiling tigerb.c >> message
    C51 tigerb.c $NOPRINT $OBJECT(TIGERb.OBJ) >> message

TIGERd.OBJ: tigerd.c tiger.h
    echo Compiling tigerd.c (external data)
    echo Compiling tigerd.c >> message
    C51 tigerd.c $NOPRINT $OBJECT(TIGERd.OBJ) >> message

TIGERc.OBJ: tigerc.c tiger.h
    echo Compiling tigerc.c (checkweigher/setpoint processing)
    echo Compiling tigerc.c >> message
    C51 tigerc.c $NOPRINT $OBJECT(TIGERc.OBJ) >> message

TIGERi.OBJ: tigeri.c tiger.h
    echo Compiling tigeri.c (user interface)
    echo Compiling tigeri.c >> message
    C51 tigeri.c $NOPRINT $OBJECT(TIGERi.OBJ) >> message

TIGERf.OBJ: tigerf.c tiger.h
    echo Compiling tigerf.c (miscellaneous functions)
    echo Compiling tigerf.c >> message
    C51 tigerf.c $NOPRINT $OBJECT(TIGERf.OBJ) >> message

TIGERk.OBJ: tigerk.c tiger.h
    echo Compiling tigerk.c (keyboard and display functions)
    echo Compiling tigerk.c >> message
    C51 tigerk.c $NOPRINT $OBJECT(TIGERk.OBJ) >> message

TIGERm.OBJ: tigerm.c tiger.h
    echo Compiling tigerm.c (main process)
    echo Compiling tigerm.c >> message
    C51 tigerm.c $NOPRINT $OBJECT(TIGERm.OBJ) >> message

TIGERp.OBJ: tigerp.c tiger.h
    echo Compiling tigerp.c (print routines)
    echo Compiling tigerp.c >> message
    C51 tigerp.c $NOPRINT $OBJECT(TIGERp.OBJ) >> message

TIGERs.OBJ: tigers.c tiger.h
    echo Compiling tigers.c (startup)
    echo Compiling tigers.c >> message
    C51 tigers.c $NOPRINT $OBJECT(TIGERs.OBJ) >> message

TIGERt.OBJ: tigert.c tiger.h
    echo Compiling tigert.c (test mode)
    echo Compiling tigert.c >> message
    C51 tigert.c $NOPRINT $OBJECT(TIGERt.OBJ) >> message

TIGERw.OBJ: tigerw.c tiger.h
    echo Compiling tigerw.c (weighing)
    echo Compiling tigerw.c >> message
    C51 tigerw.c $NOPRINT $OBJECT(TIGERw.OBJ) >> message

TIGERx.OBJ: tigerx.c tiger.h
    echo Compiling tigerx.c (memory file system)
    echo Compiling tigerx.c >> message
    C51 tigerx.c $NOPRINT $OBJECT(TIGERx.OBJ) >> message

TIGERz.OBJ: tigerz.c tiger.h
    echo Compiling tigerz.c (mcode table on last position)
    echo Compiling tigerz.c >> message
    C51 tigerz.c $NOPRINT $OBJECT(TIGERz.OBJ) >> message
